plugins {
    id 'war'
}

dependencies {
    implementation project(':common')
    implementation project(':services:user:user-api')
    implementation project(':services:account:account-api')
    implementation project(':services:work:work-api')
    implementation project(':services:diagnosis:diagnosis-api')
    implementation project(':services:defense:defense-api')
    implementation project(':services:payment:payment-api')
    implementation project(':services:notification:notification-api')
    implementation project(':services:ai:ai-api')
    implementation project(':services:user:user-service')
    implementation project(':services:account:account-service')
    implementation project(':services:work:work-service')
    implementation project(':services:diagnosis:diagnosis-service')
    implementation project(':services:defense:defense-service')
    implementation project(':services:payment:payment-service')
    implementation project(':services:notification:notification-service')
    implementation project(':services:bff-service')
    implementation project(':services:ai:ai-service')

    // ?§ÌîÑÎß?
    implementation ("org.springframework:spring-context:${springVersion}")
            { exclude group: 'commons-logging', module: 'commons-logging' }
    implementation "org.springframework:spring-webmvc:${springVersion}"
    implementation "org.springframework:spring-jdbc:${springVersion}"
    implementation "org.springframework:spring-tx:${springVersion}"
    implementation 'javax.inject:javax.inject:1'

    // Spring Security (?∏Ï¶ù ?ÑÌÑ∞ Ï≤¥Ïù∏)
    implementation "org.springframework.security:spring-security-web:${securityVersion}"
    implementation "org.springframework.security:spring-security-config:${securityVersion}"

    // AOP
    implementation 'org.aspectj:aspectjrt:1.9.20'
    implementation 'org.aspectj:aspectjweaver:1.9.20'

    // JSP, SERVLET, JSTL
    implementation('javax.servlet:javax.servlet-api:4.0.1')
    compileOnly 'javax.servlet.jsp:javax.servlet.jsp-api:2.3.3'
    implementation 'javax.servlet:jstl:1.2'

    // Log4j2 Logging
    implementation 'org.apache.logging.log4j:log4j-api:2.20.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.20.0'
    implementation 'org.apache.logging.log4j:log4j-slf4j2-impl:2.20.0'

    // xml???úÍ? Ï≤òÎ¶¨
    implementation 'xerces:xercesImpl:2.12.2'

    // Lombok
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    // Jackson - Json Ï≤òÎ¶¨
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.9.4'

    // DB
    runtimeOnly 'mysql:mysql-connector-java:8.0.33'
    implementation 'com.zaxxer:HikariCP:5.1.0'
    implementation 'org.mybatis:mybatis-spring:2.1.2'
    implementation 'org.mybatis:mybatis:3.5.16'

    // Swagger (API Î¨∏ÏÑú)
    implementation 'io.springfox:springfox-swagger2:2.9.2'
    implementation 'io.springfox:springfox-swagger-ui:2.9.2'

    // ?åÏä§??
    testImplementation "org.springframework:spring-test:${springVersion}"
    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"
}
